[package]
name = "test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
qrcode-generator = "4.1.9"


[lib]
crate-type = ["cdylib", "rlib"]
